import type { AssetManifest } from "../types.js";

/**
 * 「侧滑简介卡」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Cards/alexruix_new-newt-64.html
 * 作者：alexruix（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseSlideRevealCardAsset: AssetManifest = {
  id: "uiverse-slide-reveal-card",
  title: "侧滑简介卡",
  titleEn: "Slide Reveal Card",
  description: "悬停时正面文字滑出、背面简介滑入的渐变卡。",
  category: "block",
  tags: ["uiverse","卡片","悬停","侧滑","渐变"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>侧滑简介卡</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<div class=\"card\">\r\n  <div class=\"card-front\">\r\n    <p class=\"title\">John Doe</p>\r\n    <p class=\"subtitle\">Web Dev</p>\r\n  </div>\r\n  <div class=\"card-back\">\r\n    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\r\n  </div>\r\n</div>\r\n<style>\r\n/* From Uiverse.io by alexruix - Tags: simple, gradient, card, hover, smooth, dark, about me */\r\n.card {\r\n  color: #1b1b1b;\r\n  width: 190px;\r\n  height: 254px;\r\n  position: relative;\r\n  outline: 6px solid #f5f5f5;\r\n  border-radius: 8px;\r\n  line-height: 150%;\r\n  padding: 16px;\r\n  background: #ff930f;\r\n  background-blend-mode: multiply;\r\n  background: linear-gradient(to top, #ff930f, #ffcc33);\r\n  transition: background-color 1s ease-in-out;\r\n  overflow: hidden;\r\n}\r\n\r\n.card-front {\r\n  bottom: 16px;\r\n  left: 0;\r\n  position: absolute;\r\n  width: 100%;\r\n  text-align: center;\r\n  transition: transform 1s cubic-bezier(0.785, 0.135, 0.150, 0.860);\r\n}\r\n\r\n.card-back {\r\n  transform: translateX(120%);\r\n  transition: transform 1s cubic-bezier(0.785, 0.135, 0.150, 0.860);\r\n}\r\n\r\n\r\n/*Text*/\r\n.title {\r\n  font-size: 1.3rem;\r\n  font-weight: bold;\r\n}\r\n/*Text divider*/\r\n.title::after {\r\n  content: \"\";\r\n  display: block;\r\n  width: 50%;\r\n  border-radius: 50%;\r\n  height: 2px;\r\n  margin: 2px auto;\r\n  background-color: #1b1b1b;\r\n}\r\n\r\n\r\n/*Hover*/\r\n.card:hover {\r\n  background-color: #1b1b1b25;\r\n}\r\n\r\n.card:hover .card-front {\r\n  transform: translateX(-100%);\r\n}\r\n\r\n.card:hover .card-back {\r\n  transform: translateX(0);\r\n}\r\n\r\n\r\n\r\n</style>\n    <p class=\"uv-credit\">UIverse · alexruix · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "slide-reveal-card.html", language: "html", content: "<!--\n  侧滑简介卡 · slide-reveal-card.html\n\n  来源：github.com/uiverse-io/galaxy · Cards/alexruix_new-newt-64.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Cards/alexruix_new-newt-64.html\n  作者：alexruix（UIverse.io 社区）\n  版权：Copyright (c) alexruix\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<div class=\"card\">\r\n  <div class=\"card-front\">\r\n    <p class=\"title\">John Doe</p>\r\n    <p class=\"subtitle\">Web Dev</p>\r\n  </div>\r\n  <div class=\"card-back\">\r\n    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\r\n  </div>\r\n</div>\r\n<style>\r\n/* From Uiverse.io by alexruix - Tags: simple, gradient, card, hover, smooth, dark, about me */\r\n.card {\r\n  color: #1b1b1b;\r\n  width: 190px;\r\n  height: 254px;\r\n  position: relative;\r\n  outline: 6px solid #f5f5f5;\r\n  border-radius: 8px;\r\n  line-height: 150%;\r\n  padding: 16px;\r\n  background: #ff930f;\r\n  background-blend-mode: multiply;\r\n  background: linear-gradient(to top, #ff930f, #ffcc33);\r\n  transition: background-color 1s ease-in-out;\r\n  overflow: hidden;\r\n}\r\n\r\n.card-front {\r\n  bottom: 16px;\r\n  left: 0;\r\n  position: absolute;\r\n  width: 100%;\r\n  text-align: center;\r\n  transition: transform 1s cubic-bezier(0.785, 0.135, 0.150, 0.860);\r\n}\r\n\r\n.card-back {\r\n  transform: translateX(120%);\r\n  transition: transform 1s cubic-bezier(0.785, 0.135, 0.150, 0.860);\r\n}\r\n\r\n\r\n/*Text*/\r\n.title {\r\n  font-size: 1.3rem;\r\n  font-weight: bold;\r\n}\r\n/*Text divider*/\r\n.title::after {\r\n  content: \"\";\r\n  display: block;\r\n  width: 50%;\r\n  border-radius: 50%;\r\n  height: 2px;\r\n  margin: 2px auto;\r\n  background-color: #1b1b1b;\r\n}\r\n\r\n\r\n/*Hover*/\r\n.card:hover {\r\n  background-color: #1b1b1b25;\r\n}\r\n\r\n.card:hover .card-front {\r\n  transform: translateX(-100%);\r\n}\r\n\r\n.card:hover .card-back {\r\n  transform: translateX(0);\r\n}\r\n\r\n\r\n\r\n</style>\r\n" }],
  prompt: "请把「侧滑简介卡」装进我的项目：一张个人简介卡（约 190×254）——暖橙到黄的竖向渐变底 + 6px 浅色描边圆角；正面底部居中放姓名与职位（姓名下方一条 50% 宽的小圆角分隔条）；悬停时正面整体向左滑出（translateX -100%），背面正文以同一组 cubic-bezier(0.785,0.135,0.15,0.86) 缓动从右侧滑入（translateX 120%→0）；两张卡面都是绝对定位叠放、容器裁切，过渡 1s 带一点点先慢后快的电影感；触屏设备上点按同样触发（用 :focus-within 兜底），容器 role 语义与键盘焦点可见。先看现有卡片组件，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Cards/alexruix_new-newt-64.html", license: "CC BY 4.0（作者 alexruix · UIverse.io）" },
};
