import type { AssetManifest } from "../types.js";

/**
 * 「Material 提示气泡」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Tooltips/SteveBloX_orange-fox-41.html
 * 作者：SteveBloX（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseMaterialTooltipAsset: AssetManifest = {
  id: "uiverse-material-tooltip",
  title: "Material 提示气泡",
  titleEn: "Material Tooltip",
  description: "Material Design 3 风格提示：悬停从上方浮出带标题的卡。",
  category: "control",
  tags: ["uiverse","tooltip","material","md3","悬停"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>Material 提示气泡</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<div class=\"tooltip-container\">\r\n  <span class=\"tooltip\">\r\n    <p class=\"title\">Title</p>\r\n    <p class=\"content\">\r\n      Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n    </p>\r\n  </span>\r\n  <span class=\"text\">Material Design Tooltip</span>\r\n</div>\r\n\r\n<style>\r\n/* From Uiverse.io by SteveBloX  - Tags: material design, tooltip, shadow, md, md3 */\r\n/* Material Design 3 tooltip */\r\n.tooltip-container {\r\n  position: relative;\r\n  background: #e8def8;\r\n  color: #1d192b;\r\n  cursor: pointer;\r\n  transition: all 0.2s;\r\n  font-size: 17px;\r\n  padding: 0.7em 1.8em;\r\n  font-family: Montserrat, sans-serif;\r\n  border-radius: 50px;\r\n}\r\n.tooltip-container .text {\r\n  font-weight: bold;\r\n}\r\n\r\n.tooltip {\r\n  transform-origin: center left;\r\n  scale: 0;\r\n  position: absolute;\r\n  top: 130%;\r\n  left: 50%;\r\n  transform: translate(-50%, -10px);\r\n  transition: all 0.25s;\r\n  background: #f3edf7;\r\n  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3), 0 2px 6px 2px rgba(0, 0, 0, 0.15);\r\n  padding: 17px;\r\n  border-radius: 12px;\r\n  color: #49454f;\r\n  min-width: 312px;\r\n}\r\n\r\n.tooltip-container:hover .tooltip {\r\n  scale: 1;\r\n}\r\n\r\n.tooltip .title {\r\n  font-weight: bold;\r\n  font-size: 1em;\r\n}\r\n\r\n.tooltip .content {\r\n  font-size: 0.85em;\r\n  font-weight: semibold;\r\n}\r\n\r\n</style>\n    <p class=\"uv-credit\">UIverse · SteveBloX · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "material-tooltip.html", language: "html", content: "<!--\n  Material 提示气泡 · material-tooltip.html\n\n  来源：github.com/uiverse-io/galaxy · Tooltips/SteveBloX_orange-fox-41.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Tooltips/SteveBloX_orange-fox-41.html\n  作者：SteveBloX（UIverse.io 社区）\n  版权：Copyright (c) SteveBloX\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<div class=\"tooltip-container\">\r\n  <span class=\"tooltip\">\r\n    <p class=\"title\">Title</p>\r\n    <p class=\"content\">\r\n      Lorem ipsum dolor sit amet consectetur adipisicing elit.\r\n    </p>\r\n  </span>\r\n  <span class=\"text\">Material Design Tooltip</span>\r\n</div>\r\n\r\n<style>\r\n/* From Uiverse.io by SteveBloX  - Tags: material design, tooltip, shadow, md, md3 */\r\n/* Material Design 3 tooltip */\r\n.tooltip-container {\r\n  position: relative;\r\n  background: #e8def8;\r\n  color: #1d192b;\r\n  cursor: pointer;\r\n  transition: all 0.2s;\r\n  font-size: 17px;\r\n  padding: 0.7em 1.8em;\r\n  font-family: Montserrat, sans-serif;\r\n  border-radius: 50px;\r\n}\r\n.tooltip-container .text {\r\n  font-weight: bold;\r\n}\r\n\r\n.tooltip {\r\n  transform-origin: center left;\r\n  scale: 0;\r\n  position: absolute;\r\n  top: 130%;\r\n  left: 50%;\r\n  transform: translate(-50%, -10px);\r\n  transition: all 0.25s;\r\n  background: #f3edf7;\r\n  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3), 0 2px 6px 2px rgba(0, 0, 0, 0.15);\r\n  padding: 17px;\r\n  border-radius: 12px;\r\n  color: #49454f;\r\n  min-width: 312px;\r\n}\r\n\r\n.tooltip-container:hover .tooltip {\r\n  scale: 1;\r\n}\r\n\r\n.tooltip .title {\r\n  font-weight: bold;\r\n  font-size: 1em;\r\n}\r\n\r\n.tooltip .content {\r\n  font-size: 0.85em;\r\n  font-weight: semibold;\r\n}\r\n\r\n</style>\r\n    " }],
  prompt: "请把「Material 提示气泡」装进我的项目：一个 Material Design 3 风格 tooltip——触发文字为带小圆角胶囊底的粗体标签（浅紫底深紫字）；悬停/聚焦时上方浮出一张卡（浅紫底、圆角、双层阴影、带小箭头或缺口），卡内是标题（加粗）+ 两三行正文；浮出动画为透明度 + 轻微上移（Material 的 emphasized 缓动）；气泡 role=\"tooltip\" 并与触发元素 aria-describedby 关联，键盘聚焦同样可唤出，Esc 可关。先看现有 tooltip 体系，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Tooltips/SteveBloX_orange-fox-41.html", license: "CC BY 4.0（作者 SteveBloX · UIverse.io）" },
};
