import type { AssetManifest } from "../types.js";

/**
 * 「黏滑变色开关」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Toggle-switches/csemszepp_horrible-mouse-59.html
 * 作者：csemszepp（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseGooeyColorSwitchAsset: AssetManifest = {
  id: "uiverse-gooey-color-switch",
  title: "黏滑变色开关",
  titleEn: "Gooey Color Switch",
  description: "Gooey 滤镜做的开关：圆点黏糊地涨过去，红绿变色。",
  category: "control",
  tags: ["uiverse","开关","gooey","滤镜","创意"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>黏滑变色开关</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<input class=\"togglesw\" type=\"checkbox\">\r\n<style>\r\n/* From Uiverse.io by csemszepp - Source: https://codepen.io/t_afif/pen/PoEebrz - Tags: switch, toggle, toggle switch */\r\n.togglesw {\r\n  --s: 50px;\r\n /* adjust this to control the size*/\r\n  height: calc(var(--s) + var(--s)/5);\r\n  width: auto;\r\n /* some browsers need this */\r\n  aspect-ratio: 2.25;\r\n  border-radius: var(--s);\r\n  margin: calc(var(--s)/2);\r\n  display: grid;\r\n  cursor: pointer;\r\n  background-color: #ff7a7a;\r\n  box-sizing: content-box;\r\n  overflow: hidden;\r\n  transition: .3s .1s;\r\n  -webkit-appearance: none;\r\n  -moz-appearance: none;\r\n  appearance: none;\r\n}\r\n\r\n.togglesw:before {\r\n  content: \"\";\r\n  padding: calc(var(--s)/10);\r\n  --_g: radial-gradient(circle closest-side at calc(100% - var(--s)/2) 50%,#000 96%,#0000);\r\n  background: var(--_g) 0 /var(--_p,var(--s)) 100% no-repeat content-box,\r\n    var(--_g) var(--_p,0)/var(--s)  100% no-repeat content-box,\r\n    #fff;\r\n  mix-blend-mode: darken;\r\n  filter: blur(calc(var(--s)/12)) contrast(11);\r\n  transition: .4s, background-position .4s .1s,\r\n    padding cubic-bezier(0,calc(var(--_i,-1)*200),1,calc(var(--_i,-1)*200)) .25s .1s;\r\n}\r\n\r\n.togglesw:checked {\r\n  background-color: #85ff7a;\r\n}\r\n\r\n.togglesw:checked:before {\r\n  padding: calc(var(--s)/10 + .05px) calc(var(--s)/10);\r\n  --_p: 100%;\r\n  --_i: 1;\r\n}\r\n</style>\n    <p class=\"uv-credit\">UIverse · csemszepp · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "gooey-color-switch.html", language: "html", content: "<!--\n  黏滑变色开关 · gooey-color-switch.html\n\n  来源：github.com/uiverse-io/galaxy · Toggle-switches/csemszepp_horrible-mouse-59.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Toggle-switches/csemszepp_horrible-mouse-59.html\n  作者：csemszepp（UIverse.io 社区）\n  版权：Copyright (c) csemszepp\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<input class=\"togglesw\" type=\"checkbox\">\r\n<style>\r\n/* From Uiverse.io by csemszepp - Source: https://codepen.io/t_afif/pen/PoEebrz - Tags: switch, toggle, toggle switch */\r\n.togglesw {\r\n  --s: 50px;\r\n /* adjust this to control the size*/\r\n  height: calc(var(--s) + var(--s)/5);\r\n  width: auto;\r\n /* some browsers need this */\r\n  aspect-ratio: 2.25;\r\n  border-radius: var(--s);\r\n  margin: calc(var(--s)/2);\r\n  display: grid;\r\n  cursor: pointer;\r\n  background-color: #ff7a7a;\r\n  box-sizing: content-box;\r\n  overflow: hidden;\r\n  transition: .3s .1s;\r\n  -webkit-appearance: none;\r\n  -moz-appearance: none;\r\n  appearance: none;\r\n}\r\n\r\n.togglesw:before {\r\n  content: \"\";\r\n  padding: calc(var(--s)/10);\r\n  --_g: radial-gradient(circle closest-side at calc(100% - var(--s)/2) 50%,#000 96%,#0000);\r\n  background: var(--_g) 0 /var(--_p,var(--s)) 100% no-repeat content-box,\r\n    var(--_g) var(--_p,0)/var(--s)  100% no-repeat content-box,\r\n    #fff;\r\n  mix-blend-mode: darken;\r\n  filter: blur(calc(var(--s)/12)) contrast(11);\r\n  transition: .4s, background-position .4s .1s,\r\n    padding cubic-bezier(0,calc(var(--_i,-1)*200),1,calc(var(--_i,-1)*200)) .25s .1s;\r\n}\r\n\r\n.togglesw:checked {\r\n  background-color: #85ff7a;\r\n}\r\n\r\n.togglesw:checked:before {\r\n  padding: calc(var(--s)/10 + .05px) calc(var(--s)/10);\r\n  --_p: 100%;\r\n  --_i: 1;\r\n}\r\n</style>\r\n" }],
  prompt: "请把「黏滑变色开关」装进我的项目：一颗创意开关——红色胶囊轨道（aspect-ratio 2.25，尺寸由 --s 变量控制）内一条白色层，圆点的「滑动」不是位移而是白色层的 radial-gradient 背景位与 padding 同步变化，再叠 mix-blend-mode:darken + blur/contrast 滤镜，做出圆点被拉长黏过去的 gooey 观感；选中时轨道转绿、圆点回到另一侧；整段过渡 0.3~0.4s，内边距用 cubic-bezier 超调回弹。用真 checkbox（appearance:none 直接样式化）承载，键盘可达。先看现有开关控件，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Toggle-switches/csemszepp_horrible-mouse-59.html", license: "CC BY 4.0（作者 csemszepp · UIverse.io）" },
};
