import type { AssetManifest } from "../types.js";

/**
 * 「箭头滑出按钮」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Buttons/0x-Sarthak_hungry-penguin-30.html
 * 作者：0x-Sarthak（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseCtaArrowButtonAsset: AssetManifest = {
  id: "uiverse-cta-arrow-button",
  title: "箭头滑出按钮",
  titleEn: "Arrow Slide CTA",
  description: "悬停时白色圆点铺满整颗按钮、箭头滑出的 CTA。",
  category: "control",
  tags: ["uiverse","按钮","悬停","cta","css"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>箭头滑出按钮</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<button class=\"cta\">\r\n  <span>Contact Us &nbsp;</span>\r\n  <svg viewBox=\"0 0 13 10\" height=\"10px\" width=\"15px\">\r\n    <path d=\"M1,5 L11,5\"></path>\r\n    <polyline points=\"8 1 12 5 8 9\"></polyline>\r\n  </svg>\r\n</button>\r\n\r\n<style>\r\n/* From Uiverse.io by 0x-Sarthak  - Tags: button, hover, rounded, animated, hover button */\r\n.cta {\r\n  position: relative;\r\n  margin: auto;\r\n  padding: 11.5px 18px;\r\n  transition: all 0.2s ease;\r\n  border: 3px solid #552da8;\r\n  border-radius: 50px;\r\n  background: #552da8;\r\n  cursor: pointer;\r\n}\r\n\r\n.cta:before {\r\n  content: \"\";\r\n  position: absolute;\r\n  top: 0;\r\n  right: 0;\r\n  display: block;\r\n  border-radius: 50px;\r\n  background: white;\r\n  width: 45px;\r\n  height: 45px;\r\n  transition: all 0.8s ease;\r\n}\r\n\r\n.cta span {\r\n  position: relative;\r\n  font-family: Montserrat;\r\n  font-size: 18px;\r\n  color: white;\r\n  font-weight: 400;\r\n  letter-spacing: 0.05em;\r\n}\r\n\r\n.cta svg {\r\n  position: relative;\r\n  top: 0;\r\n  margin-left: 10px;\r\n  fill: none;\r\n  stroke-linecap: round;\r\n  stroke-linejoin: round;\r\n  stroke: white;\r\n  stroke-width: 2;\r\n  transform: translateX(-5px);\r\n  transition: all 0.5s ease;\r\n}\r\n\r\n.cta:hover:before {\r\n  width: 100%;\r\n  background: #1c1c1c;\r\n}\r\n\r\n.cta:hover svg {\r\n  transform: translateX(0);\r\n  transition: all 2s ease;\r\n}\r\n\r\n.cta:active {\r\n  transform: scale(0.95);\r\n  transition: all 2s ease;\r\n}\r\n\r\n</style>\n    <p class=\"uv-credit\">UIverse · 0x-Sarthak · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "cta-arrow-button.html", language: "html", content: "<!--\n  箭头滑出按钮 · cta-arrow-button.html\n\n  来源：github.com/uiverse-io/galaxy · Buttons/0x-Sarthak_hungry-penguin-30.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Buttons/0x-Sarthak_hungry-penguin-30.html\n  作者：0x-Sarthak（UIverse.io 社区）\n  版权：Copyright (c) 0x-Sarthak\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<button class=\"cta\">\r\n  <span>Contact Us &nbsp;</span>\r\n  <svg viewBox=\"0 0 13 10\" height=\"10px\" width=\"15px\">\r\n    <path d=\"M1,5 L11,5\"></path>\r\n    <polyline points=\"8 1 12 5 8 9\"></polyline>\r\n  </svg>\r\n</button>\r\n\r\n<style>\r\n/* From Uiverse.io by 0x-Sarthak  - Tags: button, hover, rounded, animated, hover button */\r\n.cta {\r\n  position: relative;\r\n  margin: auto;\r\n  padding: 11.5px 18px;\r\n  transition: all 0.2s ease;\r\n  border: 3px solid #552da8;\r\n  border-radius: 50px;\r\n  background: #552da8;\r\n  cursor: pointer;\r\n}\r\n\r\n.cta:before {\r\n  content: \"\";\r\n  position: absolute;\r\n  top: 0;\r\n  right: 0;\r\n  display: block;\r\n  border-radius: 50px;\r\n  background: white;\r\n  width: 45px;\r\n  height: 45px;\r\n  transition: all 0.8s ease;\r\n}\r\n\r\n.cta span {\r\n  position: relative;\r\n  font-family: Montserrat;\r\n  font-size: 18px;\r\n  color: white;\r\n  font-weight: 400;\r\n  letter-spacing: 0.05em;\r\n}\r\n\r\n.cta svg {\r\n  position: relative;\r\n  top: 0;\r\n  margin-left: 10px;\r\n  fill: none;\r\n  stroke-linecap: round;\r\n  stroke-linejoin: round;\r\n  stroke: white;\r\n  stroke-width: 2;\r\n  transform: translateX(-5px);\r\n  transition: all 0.5s ease;\r\n}\r\n\r\n.cta:hover:before {\r\n  width: 100%;\r\n  background: #1c1c1c;\r\n}\r\n\r\n.cta:hover svg {\r\n  transform: translateX(0);\r\n  transition: all 2s ease;\r\n}\r\n\r\n.cta:active {\r\n  transform: scale(0.95);\r\n  transition: all 2s ease;\r\n}\r\n\r\n</style>\r\n    " }],
  prompt: "请把「箭头滑出按钮」装进我的项目：一颗 CTA 按钮——紫色实底胶囊 + 3px 同色描边，文字全大写带字距，右侧一枚自绘箭头 SVG；静息时按钮右端叠着一个白色圆角方块（像光点），悬停时该白块横向铺满整颗按钮（0.8s cubic-bezier 缓动）并把底色染成深色，箭头同步向左滑入归位（位移 5px→0）；按下缩到 0.95。白块用 ::before 实现，按钮保持真 button 语义与 focus-visible。先看现有主按钮体系，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Buttons/0x-Sarthak_hungry-penguin-30.html", license: "CC BY 4.0（作者 0x-Sarthak · UIverse.io）" },
};
