import type { AssetManifest } from "../types.js";

/**
 * 「iOS 风格开关」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Toggle-switches/gharsh11032000_green-liger-89.html
 * 作者：gharsh11032000（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseIosStyleSwitchAsset: AssetManifest = {
  id: "uiverse-ios-style-switch",
  title: "iOS 风格开关",
  titleEn: "iOS Style Switch",
  description: "苹果风开关：滑块放大带阴影、开启转绿。",
  category: "control",
  tags: ["uiverse","开关","ios","苹果风","css"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>iOS 风格开关</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<label class=\"switch\">\r\n  <input type=\"checkbox\">\r\n  <span class=\"slider\"></span>\r\n</label>\r\n<style>\r\n/* From Uiverse.io by gharsh11032000 - Tags: apple, switch, checkbox, toggle, toggle switch */\r\n/* The switch - the box around the slider */\r\n.switch {\r\n  font-size: 17px;\r\n  position: relative;\r\n  display: inline-block;\r\n  width: 3.5em;\r\n  height: 2em;\r\n}\r\n\r\n/* Hide default HTML checkbox */\r\n.switch input {\r\n  opacity: 0;\r\n  width: 0;\r\n  height: 0;\r\n}\r\n\r\n/* The slider */\r\n.slider {\r\n  position: absolute;\r\n  cursor: pointer;\r\n  inset: 0;\r\n  background: #9fccfa;\r\n  border-radius: 50px;\r\n  transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n}\r\n\r\n.slider:before {\r\n  position: absolute;\r\n  content: \"\";\r\n  display: flex;\r\n  align-items: center;\r\n  justify-content: center;\r\n  height: 2em;\r\n  width: 2em;\r\n  inset: 0;\r\n  background-color: white;\r\n  border-radius: 50px;\r\n  box-shadow: 0 10px 20px rgba(0,0,0,0.4);\r\n  transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n}\r\n\r\n.switch input:checked + .slider {\r\n  background: #0974f1;\r\n}\r\n\r\n.switch input:focus + .slider {\r\n  box-shadow: 0 0 1px #0974f1;\r\n}\r\n\r\n.switch input:checked + .slider:before {\r\n  transform: translateX(1.6em);\r\n}\r\n</style>\n    <p class=\"uv-credit\">UIverse · gharsh11032000 · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "ios-style-switch.html", language: "html", content: "<!--\n  iOS 风格开关 · ios-style-switch.html\n\n  来源：github.com/uiverse-io/galaxy · Toggle-switches/gharsh11032000_green-liger-89.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Toggle-switches/gharsh11032000_green-liger-89.html\n  作者：gharsh11032000（UIverse.io 社区）\n  版权：Copyright (c) gharsh11032000\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<label class=\"switch\">\r\n  <input type=\"checkbox\">\r\n  <span class=\"slider\"></span>\r\n</label>\r\n<style>\r\n/* From Uiverse.io by gharsh11032000 - Tags: apple, switch, checkbox, toggle, toggle switch */\r\n/* The switch - the box around the slider */\r\n.switch {\r\n  font-size: 17px;\r\n  position: relative;\r\n  display: inline-block;\r\n  width: 3.5em;\r\n  height: 2em;\r\n}\r\n\r\n/* Hide default HTML checkbox */\r\n.switch input {\r\n  opacity: 0;\r\n  width: 0;\r\n  height: 0;\r\n}\r\n\r\n/* The slider */\r\n.slider {\r\n  position: absolute;\r\n  cursor: pointer;\r\n  inset: 0;\r\n  background: #9fccfa;\r\n  border-radius: 50px;\r\n  transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n}\r\n\r\n.slider:before {\r\n  position: absolute;\r\n  content: \"\";\r\n  display: flex;\r\n  align-items: center;\r\n  justify-content: center;\r\n  height: 2em;\r\n  width: 2em;\r\n  inset: 0;\r\n  background-color: white;\r\n  border-radius: 50px;\r\n  box-shadow: 0 10px 20px rgba(0,0,0,0.4);\r\n  transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);\r\n}\r\n\r\n.switch input:checked + .slider {\r\n  background: #0974f1;\r\n}\r\n\r\n.switch input:focus + .slider {\r\n  box-shadow: 0 0 1px #0974f1;\r\n}\r\n\r\n.switch input:checked + .slider:before {\r\n  transform: translateX(1.6em);\r\n}\r\n</style>\r\n" }],
  prompt: "请把「iOS 风格开关」装进我的项目：一颗 iOS 风格开关——3.5em×2em 胶囊轨道，未选中是浅灰底带 1px 内阴影，滑块是白色圆点带投影停在左侧；选中时轨道转绿（约 #34C759 系），滑块平滑移到右侧并轻微放大（1.04，阴影加深）；轨道内加一层同色渐变让顶部略亮；尺寸随 font-size 缩放（全 em）。用真 checkbox（视觉隐藏）+ label 承载，键盘可达、focus-visible 有晕圈。先看现有开关控件，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Toggle-switches/gharsh11032000_green-liger-89.html", license: "CC BY 4.0（作者 gharsh11032000 · UIverse.io）" },
};
