import type { AssetManifest } from "../types.js";

/**
 * 「经典对勾复选框」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Checkboxes/adamgiebl_polite-tiger-12.html
 * 作者：adamgiebl（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseClassicCheckboxAsset: AssetManifest = {
  id: "uiverse-classic-checkbox",
  title: "经典对勾复选框",
  titleEn: "Classic Checkbox",
  description: "最经典的方框对勾复选框，勾选变蓝出白勾。",
  category: "control",
  tags: ["uiverse","复选框","对勾","表单","css"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>经典对勾复选框</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<label class=\"container\">\r\n  <input type=\"checkbox\" checked=\"checked\">\r\n  <span class=\"checkmark\"></span>\r\n</label>\r\n<style>\r\n/* From Uiverse.io by adamgiebl - Tags: checkbox */\r\n/* Customize the label (the container) */\r\n.container {\r\n  display: block;\r\n  position: relative;\r\n  padding-left: 35px;\r\n  margin-bottom: 12px;\r\n  cursor: pointer;\r\n  font-size: 22px;\r\n  user-select: none;\r\n}\r\n\r\n/* Hide the browser's default checkbox */\r\n.container input {\r\n  position: absolute;\r\n  opacity: 0;\r\n  cursor: pointer;\r\n  height: 0;\r\n  width: 0;\r\n}\r\n\r\n/* Create a custom checkbox */\r\n.checkmark {\r\n  position: absolute;\r\n  top: 0;\r\n  left: 0;\r\n  height: 25px;\r\n  width: 25px;\r\n  background-color: #ccc;\r\n}\r\n\r\n/* When the checkbox is checked, add a blue background */\r\n.container input:checked ~ .checkmark {\r\n  background-color: #2196F3;\r\n}\r\n\r\n/* Create the checkmark/indicator (hidden when not checked) */\r\n.checkmark:after {\r\n  content: \"\";\r\n  position: absolute;\r\n  display: none;\r\n}\r\n\r\n/* Show the checkmark when checked */\r\n.container input:checked ~ .checkmark:after {\r\n  display: block;\r\n}\r\n\r\n/* Style the checkmark/indicator */\r\n.container .checkmark:after {\r\n  left: 9px;\r\n  top: 5px;\r\n  width: 5px;\r\n  height: 10px;\r\n  border: solid white;\r\n  border-width: 0 3px 3px 0;\r\n  transform: rotate(45deg);\r\n}\r\n</style>\n    <p class=\"uv-credit\">UIverse · adamgiebl · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "classic-checkbox.html", language: "html", content: "<!--\n  经典对勾复选框 · classic-checkbox.html\n\n  来源：github.com/uiverse-io/galaxy · Checkboxes/adamgiebl_polite-tiger-12.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Checkboxes/adamgiebl_polite-tiger-12.html\n  作者：adamgiebl（UIverse.io 社区）\n  版权：Copyright (c) adamgiebl\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<label class=\"container\">\r\n  <input type=\"checkbox\" checked=\"checked\">\r\n  <span class=\"checkmark\"></span>\r\n</label>\r\n<style>\r\n/* From Uiverse.io by adamgiebl - Tags: checkbox */\r\n/* Customize the label (the container) */\r\n.container {\r\n  display: block;\r\n  position: relative;\r\n  padding-left: 35px;\r\n  margin-bottom: 12px;\r\n  cursor: pointer;\r\n  font-size: 22px;\r\n  user-select: none;\r\n}\r\n\r\n/* Hide the browser's default checkbox */\r\n.container input {\r\n  position: absolute;\r\n  opacity: 0;\r\n  cursor: pointer;\r\n  height: 0;\r\n  width: 0;\r\n}\r\n\r\n/* Create a custom checkbox */\r\n.checkmark {\r\n  position: absolute;\r\n  top: 0;\r\n  left: 0;\r\n  height: 25px;\r\n  width: 25px;\r\n  background-color: #ccc;\r\n}\r\n\r\n/* When the checkbox is checked, add a blue background */\r\n.container input:checked ~ .checkmark {\r\n  background-color: #2196F3;\r\n}\r\n\r\n/* Create the checkmark/indicator (hidden when not checked) */\r\n.checkmark:after {\r\n  content: \"\";\r\n  position: absolute;\r\n  display: none;\r\n}\r\n\r\n/* Show the checkmark when checked */\r\n.container input:checked ~ .checkmark:after {\r\n  display: block;\r\n}\r\n\r\n/* Style the checkmark/indicator */\r\n.container .checkmark:after {\r\n  left: 9px;\r\n  top: 5px;\r\n  width: 5px;\r\n  height: 10px;\r\n  border: solid white;\r\n  border-width: 0 3px 3px 0;\r\n  transform: rotate(45deg);\r\n}\r\n</style>\r\n" }],
  prompt: "请把「经典对勾复选框」装进我的项目：一颗经典复选框——20~25px 灰底方角方块，勾选后底色变蓝（#2196F3）并用 ::after 画白色对勾（右边框+下边框旋转 45°，勾出现时无过渡或轻微缩放）；真 checkbox 隐藏，label 包裹并可带文字说明；hover 底色略提亮，focus-visible 有外圈描边；带 disabled 态（降透明度、不响应点击）。先看现有表单控件，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Checkboxes/adamgiebl_polite-tiger-12.html", license: "CC BY 4.0（作者 adamgiebl · UIverse.io）" },
};
