import type { AssetManifest } from "../types.js";

/**
 * 「液面填充按钮」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Buttons/abuayaan01_tall-mayfly-66.html
 * 作者：abuayaan01（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseLiquidFillButtonAsset: AssetManifest = {
  id: "uiverse-liquid-fill-button",
  title: "液面填充按钮",
  titleEn: "Liquid Fill Button",
  description: "悬停时蓝色液面从底部涨满按钮的水波按钮。",
  category: "control",
  tags: ["uiverse","按钮","水波","填充","css"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>液面填充按钮</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<button class=\"button\">\r\n  <span class=\"liquid\"></span>  \r\n  <span class=\"btn-txt\">Click Me</span>\r\n</button>\r\n<style>\r\n/* From Uiverse.io by abuayaan01 - Tags: button, water, btn, waves, 3d button, Button design */\r\n.button {\r\n  background-color: #000;\r\n  border: 0px;\r\n  outline: 0px;\r\n  color: #fff;\r\n  width: 200px;\r\n  padding: 20px;\r\n  border-radius: 50px;\r\n  position: relative;\r\n  overflow: hidden;\r\n  cursor: pointer;\r\n}\r\n\r\n.liquid {\r\n  background-color: #2893eb;\r\n  width: 200px;\r\n  height: 70px;\r\n  position: absolute;\r\n  bottom: 0;\r\n  left: 0;\r\n  box-shadow: inset 5px -5px 25px #104e81,\r\n  inset -5px 0px 25px #104e81;\r\n}\r\n\r\n.liquid::after {\r\n  content: '';\r\n  width: 450px;\r\n  height: 400px;\r\n  background: #000;\r\n  z-index: 1;\r\n  position: absolute;\r\n  left: -110px;\r\n  top: -380px;\r\n  border-radius: 45%;\r\n  animation: animate 5s linear 2s infinite;\r\n}\r\n\r\n.liquid::before {\r\n  content: '';\r\n  width: 450px;\r\n  height: 400px;\r\n  background-color: rgb(68, 160, 235);\r\n  z-index: 1;\r\n  position: absolute;\r\n  left: -110px;\r\n  top: -380px;\r\n  border-radius: 40%;\r\n  animation: animate 5s linear 1.8s infinite;\r\n}\r\n\r\n.btn-txt {\r\n  position: relative;\r\n  z-index: 1;\r\n  font-size: 22px;\r\n  font-family: sans-serif;\r\n  letter-spacing: 2px;\r\n}\r\n\r\n@keyframes animate {\r\n  from {\r\n    transform: rotate(0deg);\r\n  }\r\n\r\n  to {\r\n    transform: rotate(360deg);\r\n  }\r\n}\r\n\r\n\r\n</style>\n    <p class=\"uv-credit\">UIverse · abuayaan01 · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "liquid-fill-button.html", language: "html", content: "<!--\n  液面填充按钮 · liquid-fill-button.html\n\n  来源：github.com/uiverse-io/galaxy · Buttons/abuayaan01_tall-mayfly-66.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Buttons/abuayaan01_tall-mayfly-66.html\n  作者：abuayaan01（UIverse.io 社区）\n  版权：Copyright (c) abuayaan01\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<button class=\"button\">\r\n  <span class=\"liquid\"></span>  \r\n  <span class=\"btn-txt\">Click Me</span>\r\n</button>\r\n<style>\r\n/* From Uiverse.io by abuayaan01 - Tags: button, water, btn, waves, 3d button, Button design */\r\n.button {\r\n  background-color: #000;\r\n  border: 0px;\r\n  outline: 0px;\r\n  color: #fff;\r\n  width: 200px;\r\n  padding: 20px;\r\n  border-radius: 50px;\r\n  position: relative;\r\n  overflow: hidden;\r\n  cursor: pointer;\r\n}\r\n\r\n.liquid {\r\n  background-color: #2893eb;\r\n  width: 200px;\r\n  height: 70px;\r\n  position: absolute;\r\n  bottom: 0;\r\n  left: 0;\r\n  box-shadow: inset 5px -5px 25px #104e81,\r\n  inset -5px 0px 25px #104e81;\r\n}\r\n\r\n.liquid::after {\r\n  content: '';\r\n  width: 450px;\r\n  height: 400px;\r\n  background: #000;\r\n  z-index: 1;\r\n  position: absolute;\r\n  left: -110px;\r\n  top: -380px;\r\n  border-radius: 45%;\r\n  animation: animate 5s linear 2s infinite;\r\n}\r\n\r\n.liquid::before {\r\n  content: '';\r\n  width: 450px;\r\n  height: 400px;\r\n  background-color: rgb(68, 160, 235);\r\n  z-index: 1;\r\n  position: absolute;\r\n  left: -110px;\r\n  top: -380px;\r\n  border-radius: 40%;\r\n  animation: animate 5s linear 1.8s infinite;\r\n}\r\n\r\n.btn-txt {\r\n  position: relative;\r\n  z-index: 1;\r\n  font-size: 22px;\r\n  font-family: sans-serif;\r\n  letter-spacing: 2px;\r\n}\r\n\r\n@keyframes animate {\r\n  from {\r\n    transform: rotate(0deg);\r\n  }\r\n\r\n  to {\r\n    transform: rotate(360deg);\r\n  }\r\n}\r\n\r\n\r\n</style>\r\n" }],
  prompt: "请把「液面填充按钮」装进我的项目：一颗水波填充按钮——黑色实底胶囊，内部藏一个蓝色方块作为「液面」；静息时液面停在按钮下方（不可见）；悬停时液面上升铺满整颗按钮（约 0.5s 缓动）并让文字变成深色；移开后液面退回；文字始终在上层保持可读。液面用独立元素 + overflow:hidden 实现，不靠背景切换。先看现有按钮体系，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Buttons/abuayaan01_tall-mayfly-66.html", license: "CC BY 4.0（作者 abuayaan01 · UIverse.io）" },
};
