import type { AssetManifest } from "../types.js";

/**
 * 「星芒生成按钮」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Buttons/AlimurtuzaCodes_average-liger-0.html
 * 作者：AlimurtuzaCodes（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseSparkleGenerateButtonAsset: AssetManifest = {
  id: "uiverse-sparkle-generate-button",
  title: "星芒生成按钮",
  titleEn: "Sparkle Generate Button",
  description: "悬停整颗按钮燃起紫光谱光、星芒放大的生成按钮。",
  category: "control",
  tags: ["uiverse","按钮","渐变","发光","ai"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>星芒生成按钮</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<button class=\"btn\">\r\n    <svg height=\"24\" width=\"24\" fill=\"#FFFFFF\" viewBox=\"0 0 24 24\" data-name=\"Layer 1\" id=\"Layer_1\" class=\"sparkle\">\r\n        <path d=\"M10,21.236,6.755,14.745.264,11.5,6.755,8.255,10,1.764l3.245,6.491L19.736,11.5l-6.491,3.245ZM18,21l1.5,3L21,21l3-1.5L21,18l-1.5-3L18,18l-3,1.5ZM19.333,4.667,20.5,7l1.167-2.333L24,3.5,21.667,2.333,20.5,0,19.333,2.333,17,3.5Z\"></path>\r\n    </svg>\r\n\r\n    <span class=\"text\">Generate</span>\r\n</button>\r\n<style>\r\n/* From Uiverse.io by AlimurtuzaCodes - Tags: gradient, button, stars, css effect, css button, generate */\r\n.btn {\r\n  border: none;\r\n  width: 15em;\r\n  height: 5em;\r\n  border-radius: 3em;\r\n  display: flex;\r\n  justify-content: center;\r\n  align-items: center;\r\n  gap: 12px;\r\n  background: #1C1A1C;\r\n  cursor: pointer;\r\n  transition: all 450ms ease-in-out;\r\n}\r\n\r\n.sparkle {\r\n  fill: #AAAAAA;\r\n  transition: all 800ms ease;\r\n}\r\n\r\n.text {\r\n  font-weight: 600;\r\n  color: #AAAAAA;\r\n  font-size: medium;\r\n}\r\n\r\n.btn:hover {\r\n  background: linear-gradient(0deg,#A47CF3,#683FEA);\r\n  box-shadow: inset 0px 1px 0px 0px rgba(255, 255, 255, 0.4),\r\n  inset 0px -4px 0px 0px rgba(0, 0, 0, 0.2),\r\n  0px 0px 0px 4px rgba(255, 255, 255, 0.2),\r\n  0px 0px 180px 0px #9917FF;\r\n  transform: translateY(-2px);\r\n}\r\n\r\n.btn:hover .text {\r\n  color: white;\r\n}\r\n\r\n.btn:hover .sparkle {\r\n  fill: white;\r\n  transform: scale(1.2);\r\n} \r\n</style>\n    <p class=\"uv-credit\">UIverse · AlimurtuzaCodes · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "sparkle-generate-button.html", language: "html", content: "<!--\n  星芒生成按钮 · sparkle-generate-button.html\n\n  来源：github.com/uiverse-io/galaxy · Buttons/AlimurtuzaCodes_average-liger-0.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Buttons/AlimurtuzaCodes_average-liger-0.html\n  作者：AlimurtuzaCodes（UIverse.io 社区）\n  版权：Copyright (c) AlimurtuzaCodes\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<button class=\"btn\">\r\n    <svg height=\"24\" width=\"24\" fill=\"#FFFFFF\" viewBox=\"0 0 24 24\" data-name=\"Layer 1\" id=\"Layer_1\" class=\"sparkle\">\r\n        <path d=\"M10,21.236,6.755,14.745.264,11.5,6.755,8.255,10,1.764l3.245,6.491L19.736,11.5l-6.491,3.245ZM18,21l1.5,3L21,21l3-1.5L21,18l-1.5-3L18,18l-3,1.5ZM19.333,4.667,20.5,7l1.167-2.333L24,3.5,21.667,2.333,20.5,0,19.333,2.333,17,3.5Z\"></path>\r\n    </svg>\r\n\r\n    <span class=\"text\">Generate</span>\r\n</button>\r\n<style>\r\n/* From Uiverse.io by AlimurtuzaCodes - Tags: gradient, button, stars, css effect, css button, generate */\r\n.btn {\r\n  border: none;\r\n  width: 15em;\r\n  height: 5em;\r\n  border-radius: 3em;\r\n  display: flex;\r\n  justify-content: center;\r\n  align-items: center;\r\n  gap: 12px;\r\n  background: #1C1A1C;\r\n  cursor: pointer;\r\n  transition: all 450ms ease-in-out;\r\n}\r\n\r\n.sparkle {\r\n  fill: #AAAAAA;\r\n  transition: all 800ms ease;\r\n}\r\n\r\n.text {\r\n  font-weight: 600;\r\n  color: #AAAAAA;\r\n  font-size: medium;\r\n}\r\n\r\n.btn:hover {\r\n  background: linear-gradient(0deg,#A47CF3,#683FEA);\r\n  box-shadow: inset 0px 1px 0px 0px rgba(255, 255, 255, 0.4),\r\n  inset 0px -4px 0px 0px rgba(0, 0, 0, 0.2),\r\n  0px 0px 0px 4px rgba(255, 255, 255, 0.2),\r\n  0px 0px 180px 0px #9917FF;\r\n  transform: translateY(-2px);\r\n}\r\n\r\n.btn:hover .text {\r\n  color: white;\r\n}\r\n\r\n.btn:hover .sparkle {\r\n  fill: white;\r\n  transform: scale(1.2);\r\n} \r\n</style>\r\n" }],
  prompt: "请把「星芒生成按钮」装进我的项目：一颗「生成」按钮——深灰实底大圆角胶囊，左侧一枚自绘星芒 SVG（大小星四角形）+ 粗体文字；悬停时底色切成紫罗兰渐变（#A47CF3→#683FEA），星芒放大 1.2 并变纯白，文字变白，同时叠加四层阴影：内顶白色高光、内底暗色、外圈 4px 半透明白环、以及 180px 的大范围紫色泛光；整卡上浮 2px。按下回到平面。先看现有主按钮体系，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Buttons/AlimurtuzaCodes_average-liger-0.html", license: "CC BY 4.0（作者 AlimurtuzaCodes · UIverse.io）" },
};
