import type { AssetManifest } from "../types.js";

/**
 * 「彩虹光晕按钮」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Buttons/ahmedgamal-hub_yellow-cheetah-82.html
 * 作者：ahmedgamal-hub（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseRainbowGlowButtonAsset: AssetManifest = {
  id: "uiverse-rainbow-glow-button",
  title: "彩虹光晕按钮",
  titleEn: "Rainbow Glow Button",
  description: "悬停时彩虹光带绕按钮流动的发光按钮。",
  category: "control",
  tags: ["uiverse","按钮","彩虹","发光","css"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>彩虹光晕按钮</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<button class=\"glow-on-hover\" type=\"button\">HOVER ME, THEN CLICK ME!</button>\r\n<style>\r\n/* From Uiverse.io by ahmedgamal-hub - Tags: button, animated, click animation, 2FA */\r\n.glow-on-hover {\r\n  width: 220px;\r\n  height: 50px;\r\n  border: none;\r\n  outline: none;\r\n  color: #fff;\r\n  background: #111;\r\n  cursor: pointer;\r\n  position: relative;\r\n  z-index: 0;\r\n  border-radius: 10px;\r\n}\r\n\r\n.glow-on-hover:before {\r\n  content: '';\r\n  background: linear-gradient(45deg, #ff0000, #ff7300, #fffb00, #48ff00, #00ffd5, #002bff, #7a00ff, #ff00c8, #ff0000);\r\n  position: absolute;\r\n  top: -2px;\r\n  left: -2px;\r\n  background-size: 400%;\r\n  z-index: -1;\r\n  filter: blur(5px);\r\n  width: calc(100% + 4px);\r\n  height: calc(100% + 4px);\r\n  animation: glowing 20s linear infinite;\r\n  opacity: 0;\r\n  transition: opacity .3s ease-in-out;\r\n  border-radius: 10px;\r\n}\r\n\r\n.glow-on-hover:active {\r\n  color: #000\r\n}\r\n\r\n.glow-on-hover:active:after {\r\n  background: transparent;\r\n}\r\n\r\n.glow-on-hover:hover:before {\r\n  opacity: 1;\r\n}\r\n\r\n.glow-on-hover:after {\r\n  z-index: -1;\r\n  content: '';\r\n  position: absolute;\r\n  width: 100%;\r\n  height: 100%;\r\n  background: #111;\r\n  left: 0;\r\n  top: 0;\r\n  border-radius: 10px;\r\n}\r\n\r\n@keyframes glowing {\r\n  0% {\r\n    background-position: 0 0;\r\n  }\r\n\r\n  50% {\r\n    background-position: 400% 0;\r\n  }\r\n\r\n  100% {\r\n    background-position: 0 0;\r\n  }\r\n}\r\n\r\n</style>\n    <p class=\"uv-credit\">UIverse · ahmedgamal-hub · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "rainbow-glow-button.html", language: "html", content: "<!--\n  彩虹光晕按钮 · rainbow-glow-button.html\n\n  来源：github.com/uiverse-io/galaxy · Buttons/ahmedgamal-hub_yellow-cheetah-82.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Buttons/ahmedgamal-hub_yellow-cheetah-82.html\n  作者：ahmedgamal-hub（UIverse.io 社区）\n  版权：Copyright (c) ahmedgamal-hub\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<button class=\"glow-on-hover\" type=\"button\">HOVER ME, THEN CLICK ME!</button>\r\n<style>\r\n/* From Uiverse.io by ahmedgamal-hub - Tags: button, animated, click animation, 2FA */\r\n.glow-on-hover {\r\n  width: 220px;\r\n  height: 50px;\r\n  border: none;\r\n  outline: none;\r\n  color: #fff;\r\n  background: #111;\r\n  cursor: pointer;\r\n  position: relative;\r\n  z-index: 0;\r\n  border-radius: 10px;\r\n}\r\n\r\n.glow-on-hover:before {\r\n  content: '';\r\n  background: linear-gradient(45deg, #ff0000, #ff7300, #fffb00, #48ff00, #00ffd5, #002bff, #7a00ff, #ff00c8, #ff0000);\r\n  position: absolute;\r\n  top: -2px;\r\n  left: -2px;\r\n  background-size: 400%;\r\n  z-index: -1;\r\n  filter: blur(5px);\r\n  width: calc(100% + 4px);\r\n  height: calc(100% + 4px);\r\n  animation: glowing 20s linear infinite;\r\n  opacity: 0;\r\n  transition: opacity .3s ease-in-out;\r\n  border-radius: 10px;\r\n}\r\n\r\n.glow-on-hover:active {\r\n  color: #000\r\n}\r\n\r\n.glow-on-hover:active:after {\r\n  background: transparent;\r\n}\r\n\r\n.glow-on-hover:hover:before {\r\n  opacity: 1;\r\n}\r\n\r\n.glow-on-hover:after {\r\n  z-index: -1;\r\n  content: '';\r\n  position: absolute;\r\n  width: 100%;\r\n  height: 100%;\r\n  background: #111;\r\n  left: 0;\r\n  top: 0;\r\n  border-radius: 10px;\r\n}\r\n\r\n@keyframes glowing {\r\n  0% {\r\n    background-position: 0 0;\r\n  }\r\n\r\n  50% {\r\n    background-position: 400% 0;\r\n  }\r\n\r\n  100% {\r\n    background-position: 0 0;\r\n  }\r\n}\r\n\r\n</style>\r\n" }],
  prompt: "请把「彩虹光晕按钮」装进我的项目：一颗发光按钮——深黑实底圆角矩形，背后藏一条 400% 宽的彩虹线性渐变（红橙黄绿青蓝紫循环）作为光晕层（::before，blur(5px)，向四周各扩 2px）；静息时光晕透明度 0，悬停时淡入并让渐变背景位沿 x 轴 20s 线性循环流动，形成绕按钮奔流的光带；按下时光晕收起、文字转深色。文字保持纯白粗体。先看现有按钮体系，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Buttons/ahmedgamal-hub_yellow-cheetah-82.html", license: "CC BY 4.0（作者 ahmedgamal-hub · UIverse.io）" },
};
