import type { AssetManifest } from "../types.js";

/**
 * 「昼夜字母开关」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Toggle-switches/Creatlydev_wicked-bear-73.html
 * 作者：Creatlydev（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseDayNightLetterToggleAsset: AssetManifest = {
  id: "uiverse-day-night-letter-toggle",
  title: "昼夜字母开关",
  titleEn: "Day-Night Letter Toggle",
  description: "左右字母 D/G 之间，圆点滑块滑动的开关。",
  category: "control",
  tags: ["uiverse","开关","昼夜","主题切换","css"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>昼夜字母开关</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<input type=\"checkbox\" name=\"check-toggle\" id=\"checkbox\" hidden=\"\">\r\n<label for=\"checkbox\" class=\"toggle\">\r\n  G\r\n  <div class=\"toggle__switch\">\r\n      <div class=\"toggle__circle\"></div>\r\n  </div>\r\n  D\r\n</label>\r\n<style>\r\n/* From Uiverse.io by Creatlydev - Tags: switch, toggle, creative, html, css, toggle switch */\r\n.toggle {\r\n  display: flex;\r\n  align-items: center;\r\n  gap: .2rem;\r\n  font-weight: 900;\r\n  font-size: 4rem;\r\n  color: hsl(119, 84%, 10%);\r\n  text-shadow: 0 0 2px #e8e8e8;\r\n}\r\n\r\n.toggle__switch {\r\n  --bg-toggle: hsl(0, 0%, 100%);\r\n  --bg-circle: hsl(119, 84%, 10%);\r\n  --w-toggle-switch: 150px;\r\n  --w-h-toggle-circle: 35px;\r\n  --pd-toggle-switch: .5rem;\r\n  height: 55px;\r\n  width: var(--w-toggle-switch);\r\n  background-color: var(--bg-toggle);\r\n  border-radius: 4rem;\r\n  display: flex;\r\n  align-items: center;\r\n  padding: 0 var(--pd-toggle-switch);\r\n  cursor: pointer;\r\n  transition: background-color 500ms;\r\n}\r\n\r\n.toggle__circle {\r\n  width: var(--w-h-toggle-circle);\r\n  height: var(--w-h-toggle-circle);\r\n  background-color: var(--bg-circle);\r\n  border-radius: 50%;\r\n  transition: margin 400ms ease-in-out, background-color 1000ms;\r\n}\r\n\r\n#checkbox:checked + .toggle .toggle__circle {\r\n  margin-left: calc(var(--w-toggle-switch) - (var(--pd-toggle-switch) * 2) - var(--w-h-toggle-circle));\r\n}\r\n\r\n#checkbox:checked + .toggle > .toggle__switch {\r\n  --bg-toggle: hsl(119, 84%, 10%);\r\n  --bg-circle: hsl(0, 0%, 96%);\r\n  box-shadow: 0 .3rem 5rem 0 hsla(96, 85%, 34%, 30%);\r\n}\r\n</style>\n    <p class=\"uv-credit\">UIverse · Creatlydev · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "day-night-letter-toggle.html", language: "html", content: "<!--\n  昼夜字母开关 · day-night-letter-toggle.html\n\n  来源：github.com/uiverse-io/galaxy · Toggle-switches/Creatlydev_wicked-bear-73.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Toggle-switches/Creatlydev_wicked-bear-73.html\n  作者：Creatlydev（UIverse.io 社区）\n  版权：Copyright (c) Creatlydev\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<input type=\"checkbox\" name=\"check-toggle\" id=\"checkbox\" hidden=\"\">\r\n<label for=\"checkbox\" class=\"toggle\">\r\n  G\r\n  <div class=\"toggle__switch\">\r\n      <div class=\"toggle__circle\"></div>\r\n  </div>\r\n  D\r\n</label>\r\n<style>\r\n/* From Uiverse.io by Creatlydev - Tags: switch, toggle, creative, html, css, toggle switch */\r\n.toggle {\r\n  display: flex;\r\n  align-items: center;\r\n  gap: .2rem;\r\n  font-weight: 900;\r\n  font-size: 4rem;\r\n  color: hsl(119, 84%, 10%);\r\n  text-shadow: 0 0 2px #e8e8e8;\r\n}\r\n\r\n.toggle__switch {\r\n  --bg-toggle: hsl(0, 0%, 100%);\r\n  --bg-circle: hsl(119, 84%, 10%);\r\n  --w-toggle-switch: 150px;\r\n  --w-h-toggle-circle: 35px;\r\n  --pd-toggle-switch: .5rem;\r\n  height: 55px;\r\n  width: var(--w-toggle-switch);\r\n  background-color: var(--bg-toggle);\r\n  border-radius: 4rem;\r\n  display: flex;\r\n  align-items: center;\r\n  padding: 0 var(--pd-toggle-switch);\r\n  cursor: pointer;\r\n  transition: background-color 500ms;\r\n}\r\n\r\n.toggle__circle {\r\n  width: var(--w-h-toggle-circle);\r\n  height: var(--w-h-toggle-circle);\r\n  background-color: var(--bg-circle);\r\n  border-radius: 50%;\r\n  transition: margin 400ms ease-in-out, background-color 1000ms;\r\n}\r\n\r\n#checkbox:checked + .toggle .toggle__circle {\r\n  margin-left: calc(var(--w-toggle-switch) - (var(--pd-toggle-switch) * 2) - var(--w-h-toggle-circle));\r\n}\r\n\r\n#checkbox:checked + .toggle > .toggle__switch {\r\n  --bg-toggle: hsl(119, 84%, 10%);\r\n  --bg-circle: hsl(0, 0%, 96%);\r\n  box-shadow: 0 .3rem 5rem 0 hsla(96, 85%, 34%, 30%);\r\n}\r\n</style>\r\n" }],
  prompt: "请把「昼夜字母开关」装进我的项目：一个主题开关——左右两个超大粗体字母（D 与 G，代表 Day/Glow 或自定义），中间是白色胶囊轨道，内藏一枚深色圆点；切换时圆点以 400ms ease-in-out 平滑滑到另一端，轨道底色与圆点颜色互换（500ms/1000ms 的差异化时长让颜色比位移慢半拍），并在暗态叠加一层大范围同色泛光（box-shadow 40px 级）；状态由真 checkbox 承载（视觉隐藏），label 包裹整块，focus-visible 有描边。先看现有开关/主题切换控件，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Toggle-switches/Creatlydev_wicked-bear-73.html", license: "CC BY 4.0（作者 Creatlydev · UIverse.io）" },
};
