import type { AssetManifest } from "../types.js";

/**
 * 「换字提示按钮」逐字收录（V3-3 素材库）。
 *
 * 来源：UIverse · github.com/uiverse-io/galaxy · Notifications/jyefu013_unlucky-bird-53.html
 * 作者：jyefu013（UIverse.io 社区投稿）
 * 许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）——按 CC BY 要求
 *       逐件标注原作者与 UIverse.io 出处（见 source 字段与文件头的声明块）。
 * 文件为上游片段的逐字收录（原署名注释保留在 <style> 顶部）。
 */
export const UIverseSwapTextNotificationAsset: AssetManifest = {
  id: "uiverse-swap-text-notification",
  title: "换字提示按钮",
  titleEn: "Swap Text Notification",
  description: "悬停时提示文字被放大换掉的成就通知按钮。",
  category: "control",
  tags: ["uiverse","通知","徽章","悬停","成就"],
  previewHtml: "<!doctype html>\n<html lang=\"zh-CN\">\n<head>\n<meta charset=\"utf-8\">\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n<title>换字提示按钮</title>\n<style>\n  * { box-sizing: border-box; margin: 0; }\n  html, body { height: 100%; }\n  body {\n    display: grid; place-items: center;\n    background: radial-gradient(120% 130% at 50% 0%, #10151f 0%, #0b0e15 60%, #080a10 100%);\n    font-family: system-ui, \"PingFang SC\", \"Microsoft YaHei\", sans-serif;\n    color: #cdd8ea; overflow: hidden;\n  }\n  .uv-stage { display: grid; place-items: center; gap: 14px; padding: 16px; }\n  .uv-credit { font-size: 11px; letter-spacing: 0.06em; color: #5b6b8c; user-select: none; }\n</style>\n</head>\n<body>\n  <div class=\"uv-stage\">\n<button class=\"btn\">\r\n  <span class=\"default-text\">New Level Unlocked!</span>\r\n  <span class=\"hover-text\">Congrats!</span>\r\n</button>\r\n\r\n<style>\r\n/* From Uiverse.io by jyefu013 - Tags: notification */\r\n.btn {\r\n  padding: 10px;\r\n  border-radius: 5px;\r\n  font-size: 15px;\r\n  background-color: black;\r\n  color: rgb(238, 255, 0);\r\n  position: relative;\r\n  overflow: hidden;\r\n}\r\n\r\n.default-text {\r\n  z-index: 1;\r\n}\r\n\r\n.hover-text {\r\n  position: absolute;\r\n  top: 50%;\r\n  left: 50%;\r\n  transform: translate(-50%, -50%);\r\n  opacity: 0;\r\n  transition: opacity 0.5s ease-in-out;\r\n}\r\n\r\n.btn:hover .default-text {\r\n  opacity: 0;\r\n}\r\n\r\n.btn:hover .hover-text {\r\n  opacity: 1;\r\n  animation: bounce 0.5s ease-in-out;\r\n}\r\n\r\n@keyframes bounce {\r\n  0% {\r\n    transform: scale(1);\r\n  }\r\n\r\n  25% {\r\n    transform: scale(1.2);\r\n  }\r\n\r\n  75% {\r\n    transform: scale(1.1);\r\n  }\r\n\r\n  100% {\r\n    transform: scale(1);\r\n  }\r\n}\r\n\r\n.btn:hover::after {\r\n  content: '';\r\n  position: absolute;\r\n  top: -10px;\r\n  left: -10px;\r\n  width: calc(100% + 20px);\r\n  height: calc(100% + 20px);\r\n  border-radius: 50%;\r\n  background-color: rgba(255, 255, 255, 0.5);\r\n  opacity: 0;\r\n  animation: fireworks 1s linear forwards;\r\n}\r\n\r\n@keyframes fireworks {\r\n  0% {\r\n    transform: scale(1);\r\n    opacity: 1;\r\n  }\r\n\r\n  100% {\r\n    transform: scale(4);\r\n    opacity: 0;\r\n  }\r\n}\r\n\r\n</style>\n    <p class=\"uv-credit\">UIverse · jyefu013 · CC BY 4.0</p>\n  </div>\n</body>\n</html>",
  files: [{ name: "swap-text-notification.html", language: "html", content: "<!--\n  换字提示按钮 · swap-text-notification.html\n\n  来源：github.com/uiverse-io/galaxy · Notifications/jyefu013_unlucky-bird-53.html\n  原址：https://github.com/uiverse-io/galaxy/blob/main/Notifications/jyefu013_unlucky-bird-53.html\n  作者：jyefu013（UIverse.io 社区）\n  版权：Copyright (c) jyefu013\n  许可：CC BY 4.0（uiverse.io 站点条款；仓库 LICENSE 另标 MIT）\n\n  署名要求：CC BY 4.0 要求署名原作者与 UIverse.io。\n\n  以下为上游源码逐字收录（原文未改动；本声明块为收录时新增）。\n-->\n<button class=\"btn\">\r\n  <span class=\"default-text\">New Level Unlocked!</span>\r\n  <span class=\"hover-text\">Congrats!</span>\r\n</button>\r\n\r\n<style>\r\n/* From Uiverse.io by jyefu013 - Tags: notification */\r\n.btn {\r\n  padding: 10px;\r\n  border-radius: 5px;\r\n  font-size: 15px;\r\n  background-color: black;\r\n  color: rgb(238, 255, 0);\r\n  position: relative;\r\n  overflow: hidden;\r\n}\r\n\r\n.default-text {\r\n  z-index: 1;\r\n}\r\n\r\n.hover-text {\r\n  position: absolute;\r\n  top: 50%;\r\n  left: 50%;\r\n  transform: translate(-50%, -50%);\r\n  opacity: 0;\r\n  transition: opacity 0.5s ease-in-out;\r\n}\r\n\r\n.btn:hover .default-text {\r\n  opacity: 0;\r\n}\r\n\r\n.btn:hover .hover-text {\r\n  opacity: 1;\r\n  animation: bounce 0.5s ease-in-out;\r\n}\r\n\r\n@keyframes bounce {\r\n  0% {\r\n    transform: scale(1);\r\n  }\r\n\r\n  25% {\r\n    transform: scale(1.2);\r\n  }\r\n\r\n  75% {\r\n    transform: scale(1.1);\r\n  }\r\n\r\n  100% {\r\n    transform: scale(1);\r\n  }\r\n}\r\n\r\n.btn:hover::after {\r\n  content: '';\r\n  position: absolute;\r\n  top: -10px;\r\n  left: -10px;\r\n  width: calc(100% + 20px);\r\n  height: calc(100% + 20px);\r\n  border-radius: 50%;\r\n  background-color: rgba(255, 255, 255, 0.5);\r\n  opacity: 0;\r\n  animation: fireworks 1s linear forwards;\r\n}\r\n\r\n@keyframes fireworks {\r\n  0% {\r\n    transform: scale(1);\r\n    opacity: 1;\r\n  }\r\n\r\n  100% {\r\n    transform: scale(4);\r\n    opacity: 0;\r\n  }\r\n}\r\n\r\n</style>\r\n" }],
  prompt: "请把「换字提示按钮」装进我的项目：一枚成就通知按钮——黑底、黄绿色文字的圆角标签（如「New Level Unlocked!」）；悬停时原来的文字从中心放大并淡出（scale 到 4 倍同时透明度归零，像被推近镜头），同时另一句短语从下方弹入居中显示（如「Congrats!」），离开时反向回收；两段文字绝对定位叠放，容器 overflow:hidden 裁掉溢出；按钮是真 button 语义、focus-visible 有描边，深色模式下黄绿文字保持对比。先看现有 toast/通知组件，融入而不是覆盖。",
  source: { site: "UIverse", url: "https://github.com/uiverse-io/galaxy/blob/main/Notifications/jyefu013_unlucky-bird-53.html", license: "CC BY 4.0（作者 jyefu013 · UIverse.io）" },
};
