/**
 * 设计风格中文名对照（V4.6 用户反馈：Airbnb 这类原名不好理解）。
 *
 * key = 素材 id 去掉 `design-` 前缀；value = 中文展示名（品牌风保留品牌词 +
 * 中文定位词，概念风直接中文命名）。面板候选行、composer 推荐条、引用 chip
 * 统一走 resolveDesignStyleDisplayName；缺条目自动回落英文原名，不阻塞新收录。
 */
export const DESIGN_STYLE_ZH: Record<string, string> = {  agentic: "智能体对话风",
  airbnb: "Airbnb 民宿风",
  airtable: "Airtable 表格风",
  ant: "蚂蚁 Ant Design 风",
  apple: "苹果极简风",
  application: "应用程式风",
  arc: "Arc 浏览器风",
  artistic: "艺术画廊风",
  "atelier-zero": "Atelier Zero 工作室风",
  bento: "便当盒网格风",
  binance: "币安交易所风",
  "bmw-m": "宝马 M 系运动风",
  bmw: "宝马官网风",
  bold: "大胆撞色风",
  brutalism: "粗野主义",
  bugatti: "布加迪官网风",
  cafe: "咖啡馆暖调风",
  cal: "Cal 日历应用风",
  canva: "Canva 设计工具风",
  claude: "Claude AI 对话风",
  clay: "黏土拟物风",
  claymorphism: "黏土拟态",
  clean: "清爽极简风",
  clickhouse: "ClickHouse 数据风",
  cohere: "Cohere AI 风",
  coinbase: "Coinbase 交易所风",
  colorful: "缤纷多彩风",
  composio: "Composio 工具风",
  contemporary: "当代艺术风",
  corporate: "商务企业风",
  cosmic: "星际宇宙风",
  creative: "创意工作坊风",
  cursor: "Cursor 编辑器风",
  dashboard: "数据仪表盘风",
  default: "默认通用风",
  discord: "Discord 社区风",
  dithered: "抖动像素风",
  doodle: "涂鸦手绘风",
  dramatic: "戏剧化暗色风",
  duolingo: "多邻国教育风",
  editorial: "杂志编辑风",
  elegant: "优雅精致风",
  elevenlabs: "ElevenLabs 语音风",
  energetic: "活力动感风",
  enterprise: "企业级稳健风",
  expo: "Expo 开发者风",
  expressive: "表现主义风",
  fantasy: "奇幻史诗风",
  ferrari: "法拉利官网风",
  figma: "Figma 设计工具风",
  flat: "扁平化",
  framer: "Framer 建站风",
  friendly: "亲和友好风",
  futuristic: "未来科技风",
  github: "GitHub 开发者风",
  glassmorphism: "玻璃拟态",
  gradient: "渐变光晕风",
  hashicorp: "HashiCorp 基础设施风",
  huggingface: "HuggingFace 社区风",
  ibm: "IBM 企业风",
  intercom: "Intercom 客服风",
  kami: "Kami 和风",
  kraken: "Kraken 交易所风",
  lamborghini: "兰博基尼官网风",
  levels: "Levels 财经风",
  "linear-app": "Linear 项目管理风",
  lingo: "Lingo 学习风",
  lovable: "Lovable 建站风",
  luxury: "奢侈品高定风",
  mastercard: "万事达卡风",
  material: "Material Design",
  meta: "Meta 社交风",
  minimal: "极简主义",
  minimax: "MiniMax AI 风",
  mintlify: "Mintlify 文档风",
  miro: "Miro 白板协作风",
  "mission-control": "任务控制台风",
  "mistral-ai": "Mistral AI 风",
  modern: "现代简约风",
  mongodb: "MongoDB 数据库风",
  mono: "单色极简风",
  neobrutalism: "新粗野主义",
  neon: "霓虹灯夜色风",
  neumorphism: "新拟态",
  nike: "耐克运动风",
  notion: "Notion 文档风",
  nvidia: "英伟达科技风",
  ollama: "Ollama 本地 AI 风",
  openai: "OpenAI 风",
  "opencode-ai": "OpenCode 风格",
  pacman: "吃豆人像素风",
  paper: "纸质拟物风",
  perplexity: "Perplexity 搜索风",
  perspective: "透视立体风",
  pinterest: "Pinterest 瀑布流风",
  playstation: "PlayStation 游戏风",
  posthog: "PostHog 数据风",
  premium: "高端质感风",
  professional: "专业沉稳风",
  publication: "刊物出版风",
  raycast: "Raycast 启动器风",
  refined: "精雕细琢风",
  renault: "雷诺汽车风",
  replicate: "Replicate AI 风",
  resend: "Resend 邮件风",
  retro: "复古风",
  revolut: "Revolut 金融风",
  runwayml: "Runway AI 视频风",
  sanity: "Sanity 内容平台风",
  sentry: "Sentry 监控风",
  shadcn: "shadcn/ui 组件风",
  shopify: "Shopify 电商风",
  simple: "素雅简约风",
  skeumorphism: "拟物化",
  sleek: "流线光洁风",
  spacex: "SpaceX 航天风",
  spacious: "宽松留白风",
  spotify: "Spotify 音乐风",
  starbucks: "星巴克咖啡风",
  storytelling: "故事叙事风",
  stripe: "Stripe 支付风",
  supabase: "Supabase 后端云风",
  superhuman: "Superhuman 邮箱风",
  tesla: "特斯拉官网风",
  tetris: "俄罗斯方块像素风",
  theverge: "The Verge 科技媒体风",
  "together-ai": "Together AI 风",
  "totality-festival": "Totality 音乐节风",
  uber: "Uber 出行风",
  urdu: "乌尔都文排版风",
  vercel: "Vercel 部署风",
  vibrant: "活泼撞色风",
  vintage: "复古怀旧风",
  vodafone: "沃达丰电信风",
  voltagent: "VoltAgent 风格",
  "warm-editorial": "暖调编辑风",
  warp: "Warp 终端风",
  webflow: "Webflow 建站风",
  wired: "Wired 科技杂志风",
  wise: "Wise 金融风",
  "x-ai": "xAI 风",
  xiaohongshu: "小红书种草风",
  zapier: "Zapier 自动化风",
};

/** 设计风格中文展示名；新收录风格未补条目时回落英文原名。 */
export function resolveDesignStyleZhName(assetId: string, fallbackTitle: string): string {
  const bareId = assetId.replace(/^design-/, "");
  return DESIGN_STYLE_ZH[bareId] ?? fallbackTitle;
}
